/*
 * TIMERS_SHARED.h
 *
 * Created: 10/1/2021 8:45:19 PM
 *  Author: Abd-El-Rahman Sabry
 */ 


#ifndef TIMERS_SHARED_H_
#define TIMERS_SHARED_H_

typedef enum{
	
	TIMER0,
	TIMER1,
	TIMER2

}TMR_name_t;


typedef enum{
	SYNC_TMR_STOP_TIMER,
	SYNC_TMR_PRESCALER_1,
	SYNC_TMR_PRESCALER_8,
	SYNC_TMR_PRESCALER_64,
	SYNC_TMR_PRESCALER_256,
	SYNC_TMR_PRESCALER_1024,
	SYNC_TMR_EXTERNAL_CLOCK_FALLING,
	SYNC_TMR_EXTERNAL_CLOCK_RAISING
}SYNC_TMR_Precaler_t;



#define TMR_8BIT_PRESCALE(n,pre) (( (TCCR##n) &0xf8)|pre)
typedef enum
{
	NORMAL,
	PHASE_CORRECTION_PWM,
	CTC,
	FAST_PWM
}TMR_8BIT_Mode_t;





typedef enum{
	DISCONNECTED,
	TOGGLE,
	NON_INVERTING,
	INVERTING
}TMR_OC_mode_t;


typedef enum{
	ASYNC_TMR_STOP_TIMER,
	ASYNC_TMR_PRESCALER_1,
	ASYNC_TMR_PRESCALER_8,
	ASYNC_TMR_PRESCALER_32,
	ASYNC_TMR_PRESCALER_64,
	ASYNC_TMR_PRESCALER_128,
	ASYNC_TMR_PRESCALER_256,
	ASYNC_TMR_PRESCALER_1024
}ASYNC_TMR_Precaler_t;

#endif /* TIMERS_SHARED_H_ */